export const SKILL_ICONS: Record<string, string> = {
  angular: 'Angular',
  blender: 'Blender',
  bootstrap: 'Bootstrap',
  csharp: 'C#',
  css: 'CSS',
  figma: 'Figma',
  firebase: 'Firebase',
  flutter: 'Flutter',
  gimp: 'GIMP',
  git: 'Git',
  github: 'GitHub',
  heroku: 'Heroku',
  html: 'HTML',
  java: 'Java',
  javascript: 'JavaScript',
  json: 'JSON',
  postgresql: 'PostgreSQL',
  react: 'React',
  scss: 'SCSS',
  supabase: 'Supabase',
  swagger: 'Swagger',
  tailwindcss: 'Tailwind CSS',
  typescript: 'TypeScript',
  unity: 'Unity',
  unreal: 'Unreal',
  vercel: 'Vercel',
};
